version: '3'

services:
  frontend:
    image: nginx
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    image: node
    working_dir: /app
    volumes:
      - ./backend:/app
    command: node server.js
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"